name: Generate Snake Animation

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  push:
    branches:
      - output

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        run: |
          # Commands to generate the snake.svg file
          # Ensure that snake.svg is saved to the correct path

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add snake.svg
          git commit -m "Generate snake animation"
          git push
